apiVersion: v1
kind: Service
metadata:
  name: swe645-web-svc
  labels:
    app: swe645-web
spec:
  type: NodePort
  selector:
    app: swe645-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000   # fixed so you can open exactly this port in the SG
